### ISSUE TITLE
Add ARMv7l release wheels

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [aviramha/ormsgpack#100]
Hi,

Thanks for a great tool! I would like to add `ormsgpack` to an embedded linux application that runs on an `armv7l` system. Would be great to have the wheel shipped via `pypi`.

**Comment by aviramha** [comment]
> Hi,
> 
> Thanks for a great tool! I would like to add `ormsgpack` to an embedded linux application that runs on an `armv7l` system. Would be great to have the wheel shipped via `pypi`.

Hi, you're welcome. I don't have the capacity right now to do it, but if you'll do a PR I'll be glad to merge it :)

**Comment by Weezytoughtem** [comment]
>>> import ormsgpack, json, rapidjson
>>>
def default(obj):
    if isinstance(obj, decimal.Decimal):
        return str(obj)

>>> ormsgpack.unpackb(ormsgpack.packb({"set":{1, 2}}, default=default))
{'set': None}

**Comment by drewm1980** [comment]
Related, I'm trying to build for aarch64:

https://github.com/aviramha/ormsgpack/issues/142
