### ISSUE TITLE
Add support ExtType

### ISSUE THREAD

**Issue by KenKi0** [aviramha/ormsgpack#154]
I use socketio. In client side used msgpack libraries that support ExtType and socketio use it to ping.
ExtType in msgpack-python
https://github.com/msgpack/msgpack-python#ext-type
If i try to unpackb content, i got message `ValueError: invalid type: newtype struct, expected msgpack`

**Comment by aviramha** [comment]
Sorry, probably we don't support this feature. If you'd like you can send a PR and I'll review.

**Comment by exg** [comment]
There is now a feature branch with support for MessagePack extension type: https://github.com/exg/ormsgpack/tree/ext-type

**Comment by exg** [comment]
Released in the 1.4.0 release.
