### ISSUE TITLE
maturin 0.11.0 now can package type stub file for you

### ISSUE THREAD

**Issue by messense** [aviramha/ormsgpack#19]
https://github.com/PyO3/maturin/pull/567

FYI.

**Comment by aviramha** [comment]
Thanks for the heads up. I tried to update it now and found it introduced issues in the library.
I have created https://github.com/PyO3/maturin/issues/591 for followup on the issue. I'm holding update until then :)

**Comment by aviramha** [comment]
Closed by merging #23
