### ISSUE TITLE
add aarch64 pre-built wheels

### ISSUE THREAD

**Issue by asafalon1** [aviramha/ormsgpack#207]
as apple's new CPUs begin to pick up in popularity it might be useful to have wheels pre-built for their architecture in pypi.

**Comment by exg** [comment]
universal2 wheels, supporting macOS x86_64 and arm64, are already available.

**Comment by asafalon1** [comment]
I had to compile it locally when using docker on a new MacOS because the docker image I made runs on a linux, i.e. linux-aarch64

**Comment by exg** [comment]
Ah I see. Adding wheels for linux aarch64 and armv7l (#100) is on my todo list.
