### ISSUE TITLE
Segmentation fault with simple code and Python 3.11

### ISSUE THREAD

**Issue by vincbo** [aviramha/ormsgpack#223]
The following code

```
import ormsgpack

ormsgpack.packb("hello")
```

leads to a segmentation fault on the following configurations:

ormsgpack 1.4.1 + Python 3.11.7 on Debian 12
ormsgpack 1.4.1 + Python 3.11.6 on macOS sonoma 14.2.1

To reproduce, copy the content in file called test.py for example and execute the command:

```
python3 test.py
```

The example works fine with Python 3.9.16 and Python 3.10.10.

**Comment by exg** [comment]
Thanks for the report. I opened a pull request to fix the issue.
