### ISSUE TITLE
Streaming unpacking

### ISSUE THREAD

**Issue by kevinhu** [aviramha/ormsgpack#227]
I'm thinking about using ormsgpack in a project as a replacement for newline-delimited JSONs, and one feature that would be helpful is support for reading/writing items iteratively. For instance, msgpack-python lets you declare an [Unpacker](https://github.com/msgpack/msgpack-python?tab=readme-ov-file#streaming-unpacking) that yields objects as they're parsed.

Is there any way to achieve a similar functionality with ormsgpack on the parser level or by using a custom delimiter?

**Comment by exg** [comment]
> Hello. I don't understand the reason behind framing. Isn't there enough framing in tcp/ip protocol?

No, TCP is a byte-oriented protocol, so it is not enough in cases where one needs to stream a sequence of messages, as some framing protocol is needed in order for the application to know the message boundaries.

> Should a programmer invent framing protocol when just streaming `write(packb(data))` to a file? The simpler the better, isn't it?

In the case where one needs to stream a single message, object or the like, then yes there is no need for a framing protocol.
