### ISSUE TITLE
can not get tag and data from `Ext`

### ISSUE THREAD

**Issue by trim21** [aviramha/ormsgpack#286]
there is no way to get `Ext` tag and data from decoded `ormsgpack.Ext` type, unless users use defined their own `Ext` type again as ext hook.

**Comment by exg** [comment]
That is by design. `Ext` objects should only be used to request serialization in MessagePack Ext format.

**Comment by trim21** [comment]
This issue was about the impossibility to roundtrip custom extension types with the old `rmp-serde`-based deserializer (pre-v1.7.0): `ormsgpack.Ext` objects had no `.tag`/`.data` attributes, so you couldn't inspect them after unpacking.

This has been resolved since v1.7.0 (commit 689f0cb, Oct 2024) which rewrote the deserializer. The new implementation passes `(code, data)` directly to the `ext_hook` callback, so extension types roundtrip correctly.
