### ISSUE TITLE
Missing 3.10 wheels

### ISSUE THREAD

**Issue by TariqTNO** [aviramha/ormsgpack#79]
Whilst installing this library on Python 3.10 I noticed, that 3.10 wheels are only present for manylinux and not for other platforms.

I think that adding 3.10 at the remaining distros [here](https://github.com/aviramha/ormsgpack/blob/master/.github/workflows/release.yml) should do the trick.

**Comment by aviramha** [comment]
Thanks! Fixed in https://github.com/aviramha/ormsgpack/pull/82
